### ISSUE TITLE
unhandled exception  0x00007FFE1DA8C7F8 (mrt100_app.dll) on push call button (number present)

### ISSUE THREAD

**Issue by cooked71** [WOA-Project/woadialer#15]
on xl 18362, driver pack 1909 240819 (and previous), commit fccb7ee0591f77c60ec318cc3009f45b1ed6eeef (and previous), during remote debug (VS 2019), on push call button, the call is placed  but the debug stucks on this exception
![image](https://user-images.githubusercontent.com/53344663/63637206-57089200-c67a-11e9-9c03-928e03791759.png)

on release it crashes on call button push
thanks for attention

**Comment by DjArt** [comment]
Can you reproduce this with these project settings: ARM(not ARM64) arch and Debug/Release mode?
Seems like string align mismatch.

**Comment by cooked71** [comment]
> Can you reproduce this with these project settings: ARM(not ARM64) arch and Debug/Release mode?
> Seems like string align mismatch.

On arm64 you will switched on dialing page for numbers less than 10 char, Ie. if i call 191 (in italy is operator assistance) i will have all ok, can close call, etc. But if i call a regular number (in italy is 10 char with no national prefix) it will drop the exception and crash, and need to reboot all the device to have the app running again. Going to test on arm debug build

**Comment by cooked71** [comment]
> > Can you reproduce this with these project settings: ARM(not ARM64) arch and Debug/Release mode?
> > Seems like string align mismatch.
> 
> On arm64 you will switched on dialing page for numbers less than 10 char, Ie. if i call 191 (in italy is operator assistance) i will have all ok, can close call, etc. But if i call a regular number (in italy is 10 char with no national prefix) it will drop the exception and crash, and need to reboot all the device to have the app running again. Going to test on arm debug build

**Comment by cooked71** [comment]
> > > Can you reproduce this with these project settings: ARM(not ARM64) arch and Debug/Release mode?
> > > Seems like string align mismatch.
> > 
> > 
> > On arm64 you will switched on dialing page for numbers less than 10 char, Ie. if i call 191 (in italy is operator assistance) i will have all ok, can close call, etc. But if i call a regular number (in italy is 10 char with no national prefix) it will drop the exception and crash, and need to reboot all the device to have the app running again. Going to test on arm debug build

same behaviour on ARM arch, but i was not able to catch debug data

**Comment by cooked71** [comment]
> > > Can you reproduce this with these project settings: ARM(not ARM64) arch and Debug/Release mode?
> > > Seems like string align mismatch.
> > 
> > 
> > On arm64 you will switched on dialing page for numbers less than 10 char, Ie. if i call 191 (in italy is operator assistance) i will have all ok, can close call, etc. But if i call a regular number (in italy is 10 char with no national prefix) it will drop the exception and crash, and need to reboot all the device to have the app running again. Going to test on arm debug build

same behaviour on ARM arch but I was not able to catch debug data

**Comment by cooked71** [comment]
after redeployed last woa driver pack, recloned source and rebuild the app the issue disappeared, idk corrupted windows ? thanks for your time

**Comment by DjArt** [comment]
Hmmm, did you sync contacts before testing WoADialer?

**Comment by DjArt** [comment]
Because if no, it looks like extended version of this bug: https://github.com/WOA-Project/woadialer/issues/10

**Comment by cooked71** [comment]
Unfortunately at the moment of test i had 10 or 15 contacts for test, and the issue was not present, but when i synced contacts from MS account (more than 300 contacts i didnt count but it is huge) it has broken the app again ... busy atm. need to test on test local account with no contacts

**Comment by DjArt** [comment]
#10 was fixed, try reproduce bug

**Comment by cooked71** [comment]
OK issue seems to be killed by rel 0.1.200.0, great Job ! under MS account synced around 2000 contacts (i've extimated) seems good.
