### ISSUE TITLE
rel 0.1.200.0 dial interface + incoming ui: accept call button is working but ..

### ISSUE THREAD

**Issue by cooked71** [WOA-Project/woadialer#17]
dial interface + incoming ui: accept call button is working, woadilaer opens the call-active interface but the call is not active (the dialing device continues ringing)

woa 18362 driver pack 1909 updated on 08-26-2019 950 xl SS

**Comment by DjArt** [comment]
It is driver pack issue. Issue will be closed when fix will be published.

**Comment by cooked71** [comment]
> It is driver pack issue. Issue will be closed when fix will be published.

testing now

**Comment by DjArt** [comment]
https://github.com/WOA-Project/MSM8994-8992-NT-ARM64-Drivers/commit/0ee36a8d18287460421e188e01e23706d1223eee fixed
