### ISSUE TITLE
Calls not closing

### ISSUE THREAD

**Issue by theworden** [WOA-Project/woadialer#2]
Hello! Tried using the dialer. Works good to dial out. When I close the call, it doesn't end it. I let is sit for over a minute with no change in the status. I made sure WoaDialerHelper.exe is running and phonesvc is as well. Let me know what I can provide to help work it out. Thanks!

**Comment by Simizfo** [comment]
Hello! I have no logging in the app at the moment, I'll have some implemented soon so you can send me a log when you hit bugs.

Thanks for trying the app! I'd suggest running the installer again as it's a simple batch script at the moment and it's not fail-proof. Check if you have a woadialerhelper registry entry in HKEY_CLASSES_ROOT and a woadialerhelper task in task scheduler.

Thanks again :)

**Comment by theworden** [comment]
OK ran the installer again checked out the registry! There is an entry for woadialerhelper in HKEY_CLASSES_ROOT. Default is set to URL:WoADialerHelper Protocol and there's an empty key named URL Protocol. Drilling down into it We have the DefaultIcon key, and under shell --> open --> command the default key is set to "C:\WoADialerHelper\WoaDialerHelper.exe" "%1" 
WoADialerTask is running as well. Still getting the same results when trying to use. 
I'll keep an eye out for the next update. Thanks for your work so far! Let me know if there is more information I can provide in the meantime.

**Comment by Simizfo** [comment]
This should be fixed in the current code version. We now properly close calls like every other phone, no workaround anymore. Be sure to thank @DjArt for this! We'll have a new release soon so you can try it.

**Comment by DjArt** [comment]
Closing calls was fixed at https://github.com/WOA-Project/woadialer/commit/2b11796933744c481913787a18885ea8ff4ab667
