### ISSUE TITLE
On-Hold Icon overlays Speaker-Phone Icon

### ISSUE THREAD

**Issue by Revelation1714** [WOA-Project/woadialer#27]
In current Commit, as of 01/01/2020, On Lumia 950, Windows Build 1909, while on a call the On-Hold Icon overlays the speaker phone icon and you cannot click on the Speaker Phone.
I was able to fix this by editing the CallUIPage.xaml and changing the HorizontalAlignment attributes, since they were both set to "centered" and Grid.Column="2", I changed the SpeakerPhone to Left aligned and the OnHold to Right aligned and redistributed to my device and it works.
The changed lines are as follows:

<AppBarToggleButton x:Name="speakerOutputButton"  Grid.Column="2" Label="Speaker" Width="100" **HorizontalAlignment="Left"** Style="{ThemeResource AppBarToggleButtonRevealStyle}" Height="56" Checked="SpeakerOutputButton_Checked" Unchecked="SpeakerOutputButton_Unchecked">
                        <FontIcon Glyph="&#xE767;" FontFamily="Segoe MDL2 Assets"/>
                    </AppBarToggleButton>
                    <AppBarToggleButton x:Name="abtb_Hold"  Grid.Column="2" Label="Hold" Width="100" **HorizontalAlignment="Right"** Style="{ThemeResource AppBarToggleButtonRevealStyle}" Height="56" Unchecked="Abtb_Hold_Unchecked" Checked="Abtb_Hold_Checked">
                        <FontIcon Glyph="&#xE767;" FontFamily="Segoe MDL2 Assets"/>
                    </AppBarToggleButton>

**Comment by gus33000** [comment]
Fixed by 4ef5d49
