### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by chiaravalle** [WOA-Project/woadialer#30]
Hello everyone.
Is a binary release available for this?
I'd like to avoid building myself, because I'd have to install Visual Studio, which is huge, especially compared to this little app.

Thanks in advance for either.

**Comment by Simizfo** [comment]
The app is installed automatically once you boot into Windows On Arm, when you deploy with WoaDeployer or with an FFU.

Is there any reason why you would need a binary release anyway?

**Comment by chiaravalle** [comment]
I don't have it

**Comment by chiaravalle** [comment]
Please, how can I dial from WoA?

**Comment by Simizfo** [comment]
First, let me say that your deploy hasn't been completed correctly. I'd suggest you to deploy again, and let the first logon tool end its job before rebooting for the first time. This tool starts once you reach the desktop after OOBE. You can check its progress in the action center, so please wait for it to complete.

In any case, here's the binary: 
[LumiaWOA Inbox Apps](https://github.com/WOA-Project/Lumia-Drivers/tree/main/components/ANYSOC/SUPPORT.DESKTOP.EXTRAS/Source/Applications/arm64)
Look for the LumiaWOA.Dialer file. BUT! I still suggest you to deploy again, you'll miss more than the dialer.

**Comment by chiaravalle** [comment]
Oh, thanks. Do I need a specific build?

**Comment by Simizfo** [comment]
If you want to use the dialer, you'll have to use builds <= 18363 (Windows version 1909). Make sure to use arm64 builds of windows. We have official guides you can follow [here](https://woa-project.github.io/LumiaWOA/guides/).

**Comment by chiaravalle** [comment]
Thanks a lot

**Comment by chiaravalle** [comment]
Just to be 100% sure, is it true I can't update from Windows Update, and doing so will break my system?

**Comment by chiaravalle** [comment]
Any feedback?

**Comment by chiaravalle** [comment]
Nevermind, I just registered in the forums, and I'll look there for answers.
Please, discard my messages.
