### ISSUE TITLE
exception from HRESULT: 0X80070490 - on call "empty" number 

### ISSUE THREAD

**Issue by cooked71** [WOA-Project/woadialer#6]
to replicate:
- open the app (note that call button is not enabled, greyed)
- call a number, do the call as usual, terminate the call
- you'll be back to the calling view, but now the calling button is active
- now if you for mistake press the call button (active) you will have the exception

hope to be useful and compliments for the great job

on lumia 950xl ss 1907 driver pack  woa ver.18362.239

**Comment by DjArt** [comment]
https://github.com/WOA-Project/woadialer/commit/89d2c4f12ce4f47854ae5dc019595e2fba1666ea fixed
